# Generated by Django 2.2.6 on 2019-11-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0010_auto_20191113_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationrun',
            name='metrics_group',
            field=models.CharField(choices=[('intercomp', 'Basic Intercomparison'), ('tc', 'Triple Collocation')], default='intercomp', max_length=30),
        ),
    ]
